import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import React from "react";
import AppBar from "@mui/material/AppBar";
import Button from "@mui/material/Button";
import Box from "@mui/material/Box";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Box sx={{ flexGrow: 1 }}>
          <AppBar position="static">
            <div style={{ padding: "20px", textAlign: "center" }}>
              <Button variant="contained" color="error" href="/">
                Go to Home Page
              </Button>
              <Button
                variant="contained"
                color="primary"
                href="/data"
                style={{ marginLeft: "10px" }}
              >
                Go to Data Page
              </Button>
              <Button
                variant="contained"
                color="secondary"
                href="/input"
                style={{ marginLeft: "10px" }}
              >
                Go to Input Page
              </Button>
            </div>
          </AppBar>
        </Box>
        {children}
      </body>
    </html>
  );
}
